// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  files: ['**/*.{js,mjs,ts,vue}'],
  rules: {
    // TypeScript specific rules
    '@typescript-eslint/no-unused-vars': [
      'error',
      {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        ignoreRestSiblings: true,
      },
    ],
    '@typescript-eslint/no-explicit-any': 'warn',
    '@typescript-eslint/no-non-null-assertion': 'warn',

    // Vue specific rules
    'vue/multi-word-component-names': 'off',
    'vue/no-v-html': 'warn',
    'vue/require-default-prop': 'error',
    'vue/require-prop-types': 'error',
    'vue/component-name-in-template-casing': [
      'error',
      'PascalCase',
      {
        registeredComponentsOnly: false,
        ignores: [
          // Vuetify components (kebab-case)
          'v-app',
          'v-main',
          'v-container',
          'v-row',
          'v-col',
          'v-card',
          'v-card-title',
          'v-card-text',
          'v-btn',
          'v-icon',
          'v-avatar',
          'v-img',
          'v-form',
          'v-text-field',
          'v-select',
          'v-checkbox',
          'v-radio',
          'v-switch',
          'v-slider',
          'v-textarea',
          'v-file-input',
          'v-autocomplete',
          'v-navigation-drawer',
          'v-app-bar',
          'v-app-bar-nav-icon',
          'v-toolbar',
          'v-toolbar-title',
          'v-spacer',
          'v-footer',
          'v-list',
          'v-list-item',
          'v-list-item-title',
          'v-list-item-subtitle',
          'v-list-item-action',
          'v-list-item-avatar',
          'v-list-item-content',
          'v-list-item-icon',
          'v-divider',
          'v-menu',
          'v-dialog',
          'v-overlay',
          'v-sheet',
          'v-expansion-panels',
          'v-expansion-panel',
          'v-expansion-panel-header',
          'v-expansion-panel-content',
          'v-tabs',
          'v-tab',
          'v-tab-item',
          'v-window',
          'v-window-item',
          'v-carousel',
          'v-carousel-item',
          'v-data-table',
          'v-data-iterator',
          'v-pagination',
          'v-progress-circular',
          'v-progress-linear',
          'v-alert',
          'v-snackbar',
          'v-banner',
          'v-chip',
          'v-badge',
          'v-tooltip',
          'v-hover',
          'v-timeline',
          'v-timeline-item',
          'v-stepper',
          'v-stepper-step',
          'v-stepper-content',
          'v-fade-transition',
          'v-slide-transition',
          'v-expand-transition',
          'v-scale-transition',
          // Third-party components
          'notifications',
        ],
      },
    ],

    // General JavaScript/TypeScript rules
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'warn',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'warn',
    'no-unused-vars': 'off', // Disabled in favor of @typescript-eslint/no-unused-vars
    'prefer-const': 'error',
    'no-var': 'error',
    'object-shorthand': 'error',
    'prefer-arrow-callback': 'error',
    'prefer-template': 'error',
    'template-curly-spacing': 'error',
    'prefer-rest-params': 'error',
    'no-useless-escape': 'error',
    'no-useless-return': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-rename': 'error',
    'no-useless-constructor': 'error',

    // Disable rules that conflict with Prettier
    indent: 'off',
    'linebreak-style': 'off',
    'max-len': 'off',
    quotes: 'off',
    semi: 'off',
    'object-curly-spacing': 'off',
    'array-bracket-spacing': 'off',
    'computed-property-spacing': 'off',
    'key-spacing': 'off',
    'comma-spacing': 'off',
    'semi-spacing': 'off',
    'space-before-blocks': 'off',
    'space-before-function-paren': 'off',
    'space-in-parens': 'off',
    'space-infix-ops': 'off',
    'space-unary-ops': 'off',
    'spaced-comment': 'off',
    'rest-spread-spacing': 'off',
    'comma-dangle': 'off',
    'comma-style': 'off',
    'eol-last': 'off',
    'func-call-spacing': 'off',
    'new-parens': 'off',
    'no-multiple-empty-lines': 'off',
    'no-trailing-spaces': 'off',
  },
  ignores: [
    'node_modules/**',
    'dist/**',
    '.nuxt/**',
    '.output/**',
    '.nitro/**',
    'coverage/**',
    'generated/**',
    'public/uploads/**',
  ],
})
